// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using chancegame_backend.Models;

#nullable disable

namespace chancegame_backend.Migrations
{
    [DbContext(typeof(ChanceGameDbContext))]
    [Migration("20220224234143_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("chancegame_backend.Models.CardModel", b =>
                {
                    b.Property<int>("cardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cardId"), 1L, 1);

                    b.Property<int>("cardValue")
                        .HasColumnType("int");

                    b.Property<bool>("isClicked")
                        .HasColumnType("bit");

                    b.HasKey("cardId");

                    b.ToTable("CardModel");
                });
#pragma warning restore 612, 618
        }
    }
}
